language: python

python:
    - "2.7"

before_install:
    - sudo apt-get update -q
    - sudo apt-get install libblas-dev
    - sudo apt-get install liblapack-dev
    - sudo apt-get install gfortran
   # add for profile
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq


# Install packages
install:
    - pip install scipy
    - pip install numpy
    - pip install matplotlib
    - pip install pandas
    - pip install python-coveralls
    - pip install coverage
    - pip install nose
    - python setup.py install
# add for profile
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"
    - pip install nose-cprof
    - pip install properform

script:
    - export PYTHONIOENCODING=UTF-8
    - nosetests --with-coverage --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_TriFusion_cf2e6779b1_2
    - python -m properform Push 47.88.50.110:15554 asdf_TriFusion_cf2e6779b1_2 ./profile_TriFusion_cf2e6779b1_2



after_success:
  - bash <(curl -s https://codecov.io/bash)  -g **/progressbar/*
 #2017-08-11 17:19:28 modified at 0 #2017-08-11 17:19:33 modified at 1 #2017-08-11 17:19:38 modified at 2